cqse/teamscale-jacoco-agent

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/eu/cqse/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/eu/cqse/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/eu/cqse/teamscale/jacoco/agent/testimpact/TestImpactAgent.java
- agent/src/main/java/eu/cqse/teamscale/jacoco/util/Timer.java
- agent/src/test/java/eu/cqse/teamscale/jacoco/agent/AgentOptionsTest.java
- build.gradle
> Added interval 0 option

- agent/README.md
> Document how to obtain commit timestamp for SVN

- build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleUploadTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/Commit.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/ReportConfigurations.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/TeamscaleTaskExtension.kt
> Fix heap space error

- build.gradle
- impacted-tests-executor/src/main/java/com/teamscale/test/listeners/JUnit5TestListenerExtension.java
- impacted-tests-executor/src/main/java/org/junit/platform/console/ImpactedTestsExecutor.java
- impacted-tests-executor/src/main/java/org/junit/platform/console/tasks/AvailableTests.java
- teamscale-gradle-plugin/README.md
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleUploadTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/Commit.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/build.gradle
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/src/main/java/com/example/project/Fibonacci.java
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/src/test/java/com/example/project/FibonacciTest.java
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/src/test/java/com/example/project/JUnit5Test.java
> Merge parameterized JUnit 5 tests

- build.gradle
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
> Make TestImpacted cachable

- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/convert/Converter.java
- build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsExecutor.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListener.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptions.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/TestDescriptorUtils.java
- report-generator/src/main/java/com/teamscale/report/EDuplicateClassFileBehavior.java
- report-generator/src/main/java/com/teamscale/report/jacoco/DuplicateIgnoringCoverageBuilder.java
- report-generator/src/main/java/com/teamscale/report/jacoco/JaCoCoXmlReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/JaCoCoTestwiseReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/cache/ProbesCache.java
- report-generator/src/test/java/com/teamscale/report/jacoco/JaCoCoXmlReportGeneratorTest.java
- report-generator/src/test/java/com/teamscale/report/testwise/jacoco/JaCoCoTestwiseReportGeneratorTest.java
- teamscale-client/src/main/java/com/teamscale/client/FileLoggingInterceptor.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleClient.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServiceGenerator.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleReportTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/Reports.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/TeamscalePluginExtension.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
> Engine fixes

- build.gradle
- impacted-test-engine/build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/AutoSkippingEngineExecutionListener.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/AutoSkippingEngineExecutionListenerTest.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/SimpleTestDescriptor.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
> Fix bug which prevents usage of test factories and parameterized tests

- build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/ImpactedTestEngine.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/InternalImpactedTestEngine.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/TestDataWriter.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/AutoSkippingEngineExecutionListener.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/DelegatingTestDescriptor.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsExecutor.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsProvider.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListener.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingTestExecutor.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptions.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/TestDescriptorUtils.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/InternalImpactedTestEngineTest.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/AutoSkippingEngineExecutionListenerTest.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/SimpleTestDescriptor.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListenerTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTestCluster.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
> Auto skipping template methods

- CHANGELOG.md
- agent/README.md
- agent/src/dist/logging/logback.console.xml
- agent/src/dist/logging/logback.debug.xml
- agent/src/dist/logging/logback.rolling-file.xml
- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- agent/src/main/resources/com/teamscale/jacoco/agent/logback-default.xml
> Added HTTP endpoints for non TIA mode (#61)

- CHANGELOG.md
- TEST_IMPACT_ANALYSIS_DOC.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestExecutionWriter.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestExecution.java
> Added option to supply TestExecution result via REST endpoint

- .travis.yml
- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/util/AgentUtils.java
- agent/src/main/java/com/teamscale/jacoco/agent/util/LogDirectoryPropertyDefiner.java
- sample-app/run-with-profiler.sh
> No class dir

- agent/README.md
> document memory requirements

- .github/pull_request_template.md
- CHANGELOG.md
- agent/README.md
- report-generator/src/main/java/com/teamscale/report/jacoco/JaCoCoXmlReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/util/CommandLineLogger.java
- report-generator/src/main/java/com/teamscale/report/util/ILogger.java
> sanity-check coverage dumps and report errors in log file

- CHANGELOG.md
- agent/README.md
> Add SAP NetWeaver Java config

- build.gradle
- impacted-test-engine/build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListener.java
- teamscale-gradle-plugin/README.md
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/build.gradle
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/src/test/java/com/example/project/FailingRepeatedTest.java
> Fixed execution result for dynamic tests

- build.gradle
- impacted-test-engine/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
> Fix no tests executed

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/store/upload/teamscale/TeamscaleUploadStore.java
> Fixes startup issues with WildFly 17+

- .travis.yml
- agent/build.gradle
- build.gradle
- impacted-test-engine/build.gradle
- javaws-wrapper/build.gradle
- report-generator/build.gradle
- sample-app/build.gradle
- teamscale-client/build.gradle
- teamscale-gradle-plugin/build.gradle
> Upload test coverage to Teamscale

- README.md
- build.gradle
> fix release instructions

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/util/AgentUtils.java
- agent/src/test/java/com/teamscale/jacoco/agent/AgentOptionsParserTest.java
- sample-app/run-with-profiler.sh
> make out parameter optional with sensible default

- build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsProvider.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptions.java
- teamscale-client/src/main/java/com/teamscale/client/ITeamscaleService.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleClient.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
> Run all prioritized

- build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleReportTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
> Published plugin version 0.5.2

- CHANGELOG.md
- TEST_IMPACT_ANALYSIS_DOC.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToExecFileStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageViaHttpStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestEventHandlerStrategyBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsTest.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/JaCoCoTestwiseReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestExecution.java
> Added coverage-via-http flag

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- build.gradle
> Update JaCoCo to 0.8.5

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
> Fix commit discovery

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/git_properties/GitPropertiesLocator.java
- agent/src/test/java/com/teamscale/jacoco/agent/git_properties/GitPropertiesLocatorTest.java
- teamscale-client/src/main/java/com/teamscale/client/StringUtils.java
> CR#22230 Remove origin prefix

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsTest.java
> CR#22245 Fixed HTTP server validation for normal mode

- build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListener.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/InternalImpactedTestEngineTest.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingExecutionListenerTest.java
- report-generator/build.gradle
- report-generator/src/main/java/com/teamscale/report/jacoco/CoverageFile.java
- teamscale-client/src/main/java/com/teamscale/client/FileSystemUtils.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/BuildVersion.kt
- tia-client/src/main/java/com/teamscale/tia.client/ITestwiseCoverageAgentApi.java
> Removed runtime dependency on org.conqat.lib.commons

- settings.gradle
- system-tests/tia-client/build.gradle
- system-tests/tia-client/src/main/java/systemundertest/SystemUnderTest.java
- system-tests/tia-client/src/main/java/testframework/CustomTestFramework.java
- system-tests/tia-client/src/test/java/com/teamscale/tia/client/SystemTest.java
- system-tests/tia-client/src/test/java/com/teamscale/tia/client/TeamscaleMockServer.java
- teamscale-client/src/main/java/com/teamscale/client/ITeamscaleService.java
> Agent library test

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestEventHandlerStrategyBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestExecutionWriter.java
- agent/src/test/java/com/teamscale/jacoco/agent/testimpact/TestExecutionWriterTest.java
> don't cache test executions in memory

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/convert/ConvertCommand.java
- agent/src/main/java/com/teamscale/jacoco/agent/convert/Converter.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
> CR#22502 Fix duplicate flag for convert tool

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestEventHandlerStrategyBase.java
- agent/src/test/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategyTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgentTest.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleClient.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServer.java
> CR#23065 Fix revision handling for Teamscale upload

- .idea/codeStyles/codeStyleConfig.xml
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToExecFileStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageViaHttpStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestEventHandlerStrategyBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestExecutionWriter.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestExecution.java
Addresses issue https://jira.cqse.eu/browse/TS-23088
> add debug logging to test execution strategy

- CHANGELOG.md
- agent/src/docker/Dockerfile
> agent image did not react to SIGTERM (missing exec)

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsTest.java
Addresses issue https://jira.cqse.eu/browse/TS-23158
> use higher default dump interval (3h)

- report-generator/src/main/java/com/teamscale/report/jacoco/FilteringAnalyzer.java
> CR#0 Clarify meaning of "Filtering" in debug log

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
Addresses issue [TS-XXXXX](https://jira.cqse.eu/browse/TS-XXXXX)
> CR#23752 Fix test env

- agent/src/dist/logging/logback.console.xml
Throws class def not found exception otherwise :D
> Fix console log config

- agent/README.md
Addresses issue [TS-23818](https://jira.cqse.eu/browse/TS-23818)
- ~~[ ] Changes are tested adequately~~
- ~~[ ] Agent's README.md updated in case of user-visible changes~~
- ~~[ ] CHANGELOG.md updated~~
- ~~[ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)~~
- ~~[ ] [TGA Tutorial](https://docs.teamscale.com/tutorial/setting-up-tga-java) updated~~
- ~~[ ] [TIA Tutorial](https://docs.teamscale.com/tutorial/tia-java/) updated~~
Not necessary, only minor docs change.
> CR#23818: Fix dead link

- .idea/codeStyles/Project.xml
- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/teamscale/TeamscaleUploader.java
- agent/src/test/java/com/teamscale/jacoco/agent/AgentHttpServerTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/TestAgentOptionsBuilder.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServer.java
- teamscale-client/src/test/java/com/teamscale/client/TeamscaleServerTest.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
Addresses issue https://jira.cqse.eu/browse/TS-24326
> Saner default message

- CHANGELOG.md
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTestCluster.java
Addresses issue [TS-24351](https://jira.cqse.eu/browse/TS-24351)
> CR#24351 Add score and duration to API

- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitMultiProjectPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatingTransformer.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtils.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/IGitPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/ArtifactoryConfig.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/ProjectRevision.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/sapnwdi/DelayedSapNwdiMultiUploader.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/DelayedMultiUploaderBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/teamscale/DelayedTeamscaleMultiProjectUploader.java
- agent/src/test/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/upload/delay/DelayedCommitDescriptorRetrievalTest.java
- report-generator/src/main/java/com/teamscale/report/jacoco/CoverageFile.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServer.java
Addresses issue [TS-26443](https://jira.cqse.eu/browse/TS-26443)
> CR#26443 Implement multi-project upload

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestEventHandlerStrategyBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsProvider.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptionUtils.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptions.java
- system-tests/default-excludes-test/src/test/java/com/teamscale/tia/client/TeamscaleMockServer.java
- system-tests/tia-client-test/src/test/java/com/teamscale/tia/client/TeamscaleMockServer.java
- teamscale-client/src/main/java/com/teamscale/client/ITeamscaleService.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleClient.java
Addresses issue [TS-26693](https://cqse.atlassian.net/browse/TS-26693)
> CR#26693 Allow multiple partitions

- .idea/codeStyles/Project.xml
- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitMultiProjectPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatingTransformer.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtils.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/ProjectRevision.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/sapnwdi/DelayedSapNwdiMultiUploader.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/DelayedMultiUploaderBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/delay/DelayedUploader.java
- agent/src/test/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtilsTest.java
- report-generator/src/main/java/com/teamscale/report/jacoco/TeamscaleCoverageBuilder.java
Addresses issue [TS-21994](https://jira.cqse.eu/browse/TS-21994)
Also fixes an issue with Spring boot that came up during the use of the new debug logs: Code locations start with jar:file instead of file: and thus couldn't be parsed to locate the jar files to search for git.properties.
> Fix spring boot

- agent/README.md
Addresses issue [TS-26861](https://jira.cqse.eu/browse/TS-26861)
> Document how to enable debug logging

- CHANGELOG.md
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTestCluster.java
Addresses issue [TS-26964](https://cqse.atlassian.net/browse/TS-26964)
> Expose the rank of tests

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- tia-client/src/main/java/com/teamscale/tia.client/ITestwiseCoverageAgentApi.java
Addresses issue [TS-26982](https://cqse.atlassian.net/browse/TS-26982)
> CR#26982 Dynamic partition

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
Addresses issue [TS-27032](https://cqse.atlassian.net/browse/TS-27032)
> CR#27032 Fix tests are uploaded multiple times

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitMultiProjectPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatingTransformer.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtils.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/IGitPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/ArtifactoryConfig.java
- agent/src/test/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtilsTest.java
- agent/src/test/java/com/teamscale/jacoco/agent/upload/delay/DelayedCommitDescriptorRetrievalTest.java
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-26966)
> CR#26966 Implement vfs support

- agent/README.md
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
> Document Tomcat stop settings

- .idea/codeStyles/Project.xml
- CHANGELOG.md
- agent/build.gradle
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com.teamscale.java-convention.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- impacted-test-engine/build.gradle
- javaws-wrapper/build.gradle
- report-generator/build.gradle
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/cache/ClassCoverageLookup.java
- sample-app/build.gradle
- sample-debugging-app/build.gradle
- settings.gradle
- system-tests/default-excludes-test/build.gradle
- system-tests/tia-client-test/build.gradle
- system-tests/tia-client-tia-mode-http/build.gradle
- teamscale-client/build.gradle
- teamscale-client/src/main/java/com/teamscale/client/FileSystemUtils.java
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/GitRepositoryHelper.kt
- tia-client/build.gradle
Addresses issue [TS-27107](https://cqse.atlassian.net/browse/TS-27107)
- [-] Agent's README.md updated in case of user-visible changes
- [-] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)
- [-] [TGA Tutorial](https://docs.teamscale.com/tutorial/setting-up-tga-java) updated
- [-] [TIA Tutorial](https://docs.teamscale.com/tutorial/tia-java/) updated
> CR#27107 Updated dependencies

- CHANGELOG.md
- README.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- build.gradle
Addresses issue [TS-27246](https://cqse.atlassian.net/browse/TS-27246)
> CR#27246 Key Obfuscation

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- teamscale-client/src/main/java/com/teamscale/client/HttpUtils.java
Addresses issue [TS-26925](https://cqse.atlassian.net/browse/TS-26925)
> TS-26925: Enable SSL validation by default

- agent/README.md
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
> TS-28539: Documentation for secure communication

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsParserTest.java
Addresses issue [TS-21242](https://cqse.atlassian.net/browse/TS-21242)
> TS-21242 use https for port 443 when no scheme is provided

- .github/workflows/actions.yml
- CHANGELOG.md
- README.md
- agent/build.gradle
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
> TS-29374 Add dockerhub publishing via GitHub Action

- CHANGELOG.md
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/TestwiseCoverageCollectingTestExecutor.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptionUtils.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/options/TestEngineOptions.java
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/ReportConfigurationBase.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/build.gradle
Addresses issue [TS-29739](https://cqse.atlassian.net/browse/TS-29739)
> TS-29739 Fixes #201

- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitMultiProjectPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorUtils.java
- agent/src/test/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitPropertiesLocatorTest.java
Addresses issue [TS-29748](https://cqse.atlassian.net/browse/TS-29748)
> TS-29748 Add Support for git.properties files inside of nested jar files

- .idea/codeStyles/Project.xml
- CHANGELOG.md
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
Addresses issue [TS-29909](https://cqse.atlassian.net/browse/TS-29909)
> TS-29909 Fix test execution when collectTestwiseCoverage is false

- .githooks/pre-commit
- README.md
Addresses issue https://cqse.atlassian.net/browse/TS-30201
> tidy up pom on commit

- CHANGELOG.md
- teamscale-maven-plugin/src/main/java/com/teamscale/tia/maven/TiaMojoBase.java
Addresses issue [TS-30478](https://cqse.atlassian.net/browse/TS-30478)
fixes #214 
> put reports generated by the Maven plugin in the target dir

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/convert/Converter.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/JacocoAgentBuilder.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToTeamscaleStrategy.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageViaHttpStrategy.java
- report-generator/src/main/java/com/teamscale/report/jacoco/FilteringAnalyzer.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/JaCoCoTestwiseReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/cache/AnalyzerCache.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/cache/ProbesCache.java
Addresses issue [TS-31634](https://cqse.atlassian.net/browse/TS-31634)
> TS-31634 Speed up test coverage conversion

- CHANGELOG.md
- agent/build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com.teamscale.java-convention.gradle.kts
- common-system-test/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- impacted-test-engine/build.gradle
- javaws-wrapper/build.gradle
- report-generator/build.gradle
- system-tests/junit-run-listener-test/build.gradle
- system-tests/multiple-agents-test/build.gradle
- system-tests/tia-client-tia-mode-http/build.gradle
- system-tests/tia-maven/build.gradle
- teamscale-client/build.gradle
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/Report.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleUploadTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestwiseCoverageReportTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/JUnitReportConfiguration.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/JacocoReportConfiguration.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/ReportConfigurationBase.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/TestwiseCoverageConfiguration.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-surefire-provider/build.gradle
- tia-client/build.gradle
- tia-runlisteners/build.gradle
Addresses issue [TS-31709](https://cqse.atlassian.net/browse/TS-31709)
> TS-31709 file not found

- .github/workflows/actions.yml
- CHANGELOG.md
- README.md
- agent/build.gradle
- build.gradle
- buildSrc/src/main/kotlin/com.teamscale.java-convention.gradle.kts
- buildSrc/src/main/kotlin/com.teamscale.publish.gradle.kts
- settings.gradle
- teamscale-gradle-plugin/build.gradle
- tia-client/build.gradle
Addresses issue [TS-32120](https://cqse.atlassian.net/browse/TS-32120)
> Fixes #225

- .github/workflows/actions.yml
Addresses issue [TS-33008](https://cqse.atlassian.net/browse/TS-33008)
> TS-33008 Fixed upload to Teamscale

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/upload/artifactory/ArtifactoryConfig.java
- common-system-test/src/main/java/com/teamscale/test/commons/SystemTestUtils.java
- settings.gradle
- system-tests/artifactory-git-properties-detection/build.gradle
- system-tests/artifactory-git-properties-detection/src/main/java/systemundertest/SystemUnderTest.java
- system-tests/artifactory-git-properties-detection/src/main/resources/git.properties
- system-tests/artifactory-git-properties-detection/src/test/java/com/teamscale/client/ArtifactoryGitPropertiesDetectionTest.java
- system-tests/artifactory-git-properties-detection/src/test/java/com/teamscale/client/ArtifactoryMockServer.java
- system-tests/default-excludes-test/src/test/java/com/teamscale/tia/client/DefaultExcludesSystemTest.java
- system-tests/http-redirect-test/src/test/java/com/teamscale/client/HttpRedirectSystemTest.java
Addresses issue [TS-32982](https://cqse.atlassian.net/browse/TS-32982)
> TS-32982 Fix git.properties detection with directories

- CHANGELOG.md
- agent/README.md
Addresses issue [TS-33171](https://cqse.atlassian.net/browse/TS-33171)
> TS-33171 Fix Artifactory patterns in the docs

- CHANGELOG.md
- agent/build.gradle
- buildSrc/src/main/kotlin/PublicationInfoExtension.kt
- buildSrc/src/main/kotlin/com.teamscale.publish.gradle.kts
- buildSrc/src/main/kotlin/com.teamscale.shadow-convention.gradle.kts
- common-system-test/build.gradle
- impacted-test-engine/build.gradle
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/TestDescriptorResolverRegistry.java
- report-generator/build.gradle
- sample-debugging-app/build.gradle
- system-tests/tia-client-tia-mode-http/build.gradle
- teamscale-client/build.gradle
- teamscale-gradle-plugin/build.gradle
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/AgentPortGenerator.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscalePlugin.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/AgentConfiguration.kt
- tia-client/build.gradle
Addresses issue [TS-32994](https://cqse.atlassian.net/browse/TS-32994)
> TS-32994 Fix multiple issues faced in bigger production application

- buildSrc/src/main/kotlin/com.teamscale.publish.gradle.kts
- teamscale-maven-plugin/build.gradle
- teamscale-maven-plugin/pom.xml
Addresses issue [TS-33307](https://cqse.atlassian.net/browse/TS-33307)
> TS-33307 Fix auto-closing of Maven plugin

- CHANGELOG.md
- report-generator/build.gradle.kts
Addresses issue [TS-34267](https://cqse.atlassian.net/browse/TS-34267)
> TS-34267 Fix Gradle module metadata

- CHANGELOG.md
- common-system-test/src/main/java/com/teamscale/test/commons/ExternalReport.java
- common-system-test/src/main/java/com/teamscale/test/commons/TeamscaleMockServer.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsSorter.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/engine/NoImpactedTestsTest.java
- system-tests/default-excludes-test/src/test/java/com/teamscale/tia/client/DefaultExcludesSystemTest.java
- teamscale-gradle-plugin/build.gradle.kts
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/Report.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TeamscaleUploadTask.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestImpacted.kt
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/config/ReportConfigurationBase.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TestwiseCoverageReportAssert.kt
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/build.gradle
Addresses issue [TS-34273](https://cqse.atlassian.net/browse/TS-34273)
> TS-34273 Fix Gradle plugin partition evaluation

- .github/workflows/actions.yml
Addresses issue [TS-34847](https://cqse.atlassian.net/browse/TS-34847)
> TS-34847 Upload only tagged versions to DockerHub

- CHANGELOG.md
- report-generator/src/main/java/com/teamscale/report/jacoco/FilteringAnalyzer.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/CachingExecutionDataReader.java
- teamscale-gradle-plugin/src/main/kotlin/com/teamscale/TestwiseCoverageReportTask.kt
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- teamscale-gradle-plugin/src/test/resources/calculator_groovy/build.gradle
Addresses issue [TS-34739](https://cqse.atlassian.net/browse/TS-34739)
> TS-34739 Fix broken logging

- CHANGELOG.md
- README.md
- agent/build.gradle.kts
- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- gradle/libs.versions.toml
- renovate.json
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
Addresses issue [TS-34298](https://cqse.atlassian.net/browse/TS-34298)
> TS-34298 Fix warnings during test execution

- .idea/runConfigurations/SampleApp.xml
- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/JaCoCoPreMain.java
- agent/src/main/java/com/teamscale/jacoco/agent/LenientCoverageTransformer.java
- buildSrc/src/main/kotlin/TestExtension.kt
- gradle/libs.versions.toml
- report-generator/src/main/java/com/teamscale/report/jacoco/FilteringAnalyzer.java
- report-generator/src/main/java/com/teamscale/report/jacoco/JaCoCoXmlReportGenerator.java
- report-generator/src/main/java/com/teamscale/report/jacoco/OpenAnalyzer.java
- report-generator/src/main/java/com/teamscale/report/testwise/jacoco/cache/AnalyzerCache.java
- sample-debugging-app/build.gradle.kts
- sample-debugging-app/jacocoagent.properties
Addresses issue [TS-35155](https://cqse.atlassian.net/browse/TS-35155)
> TS-35155 Tolerate unsupported Java class file versions

- agent/README.md
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
- [-] CHANGELOG.md updated
- [-] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)
- [-] [TGA Tutorial](https://docs.teamscale.com/tutorial/setting-up-tga-java) updated
- [-] [TIA Tutorial](https://docs.teamscale.com/tutorial/tia-java/) updated
> TS-33942 improve doc to make testwise mode more present

- CHANGELOG.md
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/CucumberPickleDescriptorResolver.java
Addresses issue [TS-35765](https://cqse.atlassian.net/browse/TS-35765)
> TS-35765 Support Cucumber pre 7.11.2

- CHANGELOG.md
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/engine/executor/ImpactedTestsProvider.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTestCluster.java
Addresses issue [TS-35545](https://cqse.atlassian.net/browse/TS-35545)
> TS-35545 Produce proper error message on failed request

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/GenericExceptionMapper.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgent.java
- agent/src/test/java/com/teamscale/jacoco/agent/testimpact/TestwiseCoverageAgentTest.java
- common-system-test/src/main/java/com/teamscale/test/commons/TeamscaleMockServer.java
- system-tests/cucumber-maven-tia/src/test/java/com/teamscale/tia/TiaMavenCucumberSystemTest.java
- system-tests/default-excludes-test/src/test/java/com/teamscale/tia/client/DefaultExcludesSystemTest.java
- system-tests/http-redirect-test/src/test/java/com/teamscale/client/HttpRedirectSystemTest.java
- system-tests/junit-run-listener-test/src/test/java/com/teamscale/tia/client/JUnitRunListenerSystemTest.java
- system-tests/tia-client-test/src/test/java/com/teamscale/tia/client/TiaClientSystemTest.java
- system-tests/tia-maven/src/test/java/com/teamscale/tia/TiaMavenDumpToFileSystemTest.java
- system-tests/tia-maven/src/test/java/com/teamscale/tia/TiaMavenSystemTest.java
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- tia-client/src/main/java/com/teamscale/tia.client/ITestwiseCoverageAgentApi.java
- tia-client/src/main/java/com/teamscale/tia.client/TiaAgent.java
Addresses issue [TS-35987](https://cqse.atlassian.net/browse/TS-35987)
> TS-35987 Added error handling to jersey

- CHANGELOG.md
- report-generator/src/main/java/com/teamscale/report/testwise/model/PathCoverage.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/RevisionInfo.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestExecution.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestInfo.java
- report-generator/src/main/java/com/teamscale/report/testwise/model/TestwiseCoverageReport.java
- teamscale-client/src/main/java/com/teamscale/client/ClusteredTestDetails.java
- teamscale-client/src/main/java/com/teamscale/client/TestDetails.java
Addresses issue [TS-36140](https://cqse.atlassian.net/browse/TS-36140)
> TS-36140 Moshi adapter transformation issue

- CHANGELOG.md
- report-generator/src/main/java/com/teamscale/report/testwise/model/FileCoverage.java
- teamscale-client/src/main/java/com/teamscale/client/ClusteredTestDetails.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTest.java
- teamscale-client/src/main/java/com/teamscale/client/PrioritizableTestCluster.java
Addresses issue [TS-36477](https://cqse.atlassian.net/browse/TS-36477)
> TS-36477 Added more default constructors for moshi

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/CoverageToJsonStrategyBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/testimpact/TestExecutionWriter.java
- common-system-test/src/main/java/com/teamscale/test/commons/TeamscaleMockServer.java
- impacted-test-engine/src/main/java/com/teamscale/test_impacted/test_descriptor/CucumberPickleDescriptorResolver.java
- impacted-test-engine/src/test/java/com/teamscale/test_impacted/test_descriptor/CucumberPickleDescriptorResolverTest.java
- report-generator/src/main/java/com/teamscale/report/ReportUtils.java
- report-generator/src/main/java/com/teamscale/report/testwise/TestwiseCoverageReportWriter.java
- system-tests/cucumber-maven-tia/maven-project/src/test/resources/hellocucumber/calculator.feature
- system-tests/cucumber-maven-tia/src/test/java/com/teamscale/tia/TiaMavenCucumberSystemTest.java
- system-tests/tia-maven/src/test/java/com/teamscale/tia/TiaMavenDumpToFileSystemTest.java
- teamscale-client/src/main/java/com/teamscale/client/JsonUtils.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServiceGenerator.java
- teamscale-gradle-plugin/src/test/kotlin/com/teamscale/TeamscalePluginTest.kt
- tia-client/src/main/java/com/teamscale/tia.client/CommandLineInterface.java
- tia-client/src/main/java/com/teamscale/tia.client/RunningTest.java
Addresses issue [TS-36706](https://cqse.atlassian.net/browse/TS-36706)
> TS-36706 Escape Scenario Names in Cucumber

- CHANGELOG.md
- agent/README.md
- agent/src/main/java/com/teamscale/jacoco/agent/AgentBase.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptions.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- teamscale-client/build.gradle.kts
- teamscale-client/src/main/java/com/teamscale/client/HttpUtils.java
- teamscale-client/src/main/java/com/teamscale/client/ProxySystemProperties.java
- teamscale-client/src/main/java/com/teamscale/client/TeamscaleServiceGenerator.java
- teamscale-client/src/test/java/com/teamscale/client/TeamscaleServiceGeneratorProxyServerTest.java
- teamscale-client/src/test/java/com/teamscale/client/TeamscaleServiceGeneratorTest.java
Addresses issue [TS-37747](https://cqse.atlassian.net/browse/TS-37747)
> TS-37747 add new option to provide a proxy password by file

- agent/src/main/java/com/teamscale/jacoco/agent/Agent.java
- agent/src/main/java/com/teamscale/jacoco/agent/util/FileSystemUtilsClone.java
- teamscale-client/src/main/java/com/teamscale/client/FileSystemUtils.java
Addresses issue [TS-37922](https://cqse.atlassian.net/browse/TS-37922)
> TS-37922 Handling for null pointer cases added.

- CHANGELOG.md
- teamscale-maven-plugin/src/main/java/com/teamscale/maven/TeamscaleMojoBase.java
Addresses issue [TS-37972](https://cqse.atlassian.net/browse/TS-37972)
> TS-37972 add properties to end commit and revision

- CHANGELOG.md
- agent/src/docker/Dockerfile
Addresses issue [TS-38121](https://cqse.atlassian.net/browse/TS-38121)
> make docker container copy agent to /transfer if mounted

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/ResourceBase.java
- agent/src/test/java/com/teamscale/jacoco/agent/AgentHttpServerTest.java
Addresses issue [TS-38164](https://cqse.atlassian.net/browse/TS-38164)
> TS-38164 Fixed /commit and /revision endpoints

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/util/AgentUtils.java
Addresses issue [TS-39131](https://cqse.atlassian.net/browse/TS-39131)
> fix NPE when agent jar is in the root directory

- CHANGELOG.md
- installer/src/main/java/module-info.java
Addresses issue [TS-39365](https://cqse.atlassian.net/browse/TS-39365)
> add support for elliptic curve SSL ciphers

- CHANGELOG.md
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/KotlinStringTransformer.kt
- buildSrc/src/main/kotlin/com.teamscale.publish.gradle.kts
- buildSrc/src/main/kotlin/com.teamscale.shadow-convention.gradle.kts
- system-tests/kotlin-inline-function-test/build.gradle.kts
- system-tests/kotlin-inline-function-test/src/main/kotlin/foo/Main.kt
- system-tests/kotlin-inline-function-test/src/test/java/com/teamscale/tia/client/KotlinInlineFunctionTest.java
Addresses issue [TS-39443](https://cqse.atlassian.net/browse/TS-39443)
> TS-39443 Kotlin wrong coverage

- sample-debugging-app/build.gradle.kts
Addresses issue [TS-40158](https://cqse.atlassian.net/browse/TS-40158)
Below are not applicable:
> TS-40158 Add missing agent-jar plugin

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitMultiProjectPropertiesLocator.java
- agent/src/main/java/com/teamscale/jacoco/agent/commit_resolution/git_properties/GitSingleProjectPropertiesLocator.java
Addresses issue [TS-41669](https://cqse.atlassian.net/browse/TS-41669)
> TS-41669 replace class in logging init.

- CHANGELOG.md
- teamscale-client/src/main/kotlin/com/teamscale/client/ProfilerLogEntry.kt
- teamscale-client/src/main/kotlin/com/teamscale/client/TeamscaleClient.kt
Addresses issue [TS-41931](https://cqse.atlassian.net/browse/TS-41931)
> TS-41931 The details of a profiler log entry shall be nullable.

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/PreMain.java
- agent/src/main/java/com/teamscale/jacoco/agent/configuration/ConfigurationViaTeamscale.java
- agent/src/test/java/com/teamscale/jacoco/agent/options/AgentOptionsParserTest.java
- teamscale-client/src/main/kotlin/com/teamscale/client/ITeamscaleService.kt
Addresses issue [TS-42129](https://cqse.atlassian.net/browse/TS-42129)
> improve error messages when configuration via Teamscale fails

- CHANGELOG.md
- agent/src/main/java/com/teamscale/jacoco/agent/PreMain.java
- agent/src/main/java/com/teamscale/jacoco/agent/configuration/ConfigurationViaTeamscale.java
- agent/src/main/java/com/teamscale/jacoco/agent/logging/LoggingUtils.java
- agent/src/main/java/com/teamscale/jacoco/agent/options/AgentOptionsParser.java
- agent/src/test/java/com/teamscale/jacoco/agent/logging/LoggingUtilsTest.java
- sample-app/run-log-test.sh
- sample-app/run-with-profiler.sh
- teamscale-client/src/main/kotlin/com/teamscale/client/ConnectExceptionRetryInterceptor.kt
- teamscale-client/src/main/kotlin/com/teamscale/client/HttpUtils.kt
- teamscale-client/src/test/kotlin/com/teamscale/client/ConnectExceptionRetryInterceptorTest.kt
Addresses issue [TS-42124](https://cqse.atlassian.net/browse/TS-42124)
> TS-42124 Added more debug logging

- .github/workflows/actions.yml
- CHANGELOG.md
- agent/src/docker/Dockerfile
Addresses issue [TS-42362](https://cqse.atlassian.net/browse/TS-42362)
> TS-42362 Fix wrong version number in docker container
